$(function(){
  $(".uno").click(function(){
    $(".runo").slideToggle();
  });
   $(".dos").click(function(){
    $(".rdos").slideToggle();
  });
    $(".tres").click(function(){
    $(".rtres").slideToggle();
  });
    $(".cuatro").click(function(){
    $(".rcuatro").slideToggle();
  });
     $(".cinco").click(function(){
    $(".rcinco").slideToggle();
  });
     $(".seis").click(function(){
    $(".rseis").slideToggle();
  });
});