$(function(){
  $(".uno").click(function(){
    $(".runo").slideToggle();
  });
   $(".dos").click(function(){
    $(".rdos").slideToggle();
  });
    $(".tres").click(function(){
    $(".rtres").slideToggle();
  });
});